### ISSUE TITLE
Support for mutually recursive function

### ISSUE THREAD

**Issue by clause** [cojen/Maker#6]
There doesn't appear to be a way to generate mutually recursive functions.  For example, the error/code below. While this example is artifical. I ran in to the issue why trying to generate 

```
    public static <A,B> Function<A,B> Y(Function<Function<A,B>, Function<A,B>> f) {
        return x -> f.apply(Y(f)).apply(x);
    }
```

Example:

```
Exception in thread "main" java.lang.IllegalStateException: No matching methods found for: org.cojen.maker.ClassMaker-9.even
	at org.cojen.maker.Type.findMethod(Type.java:575)
	at org.cojen.maker.TheMethodMaker.doInvoke(TheMethodMaker.java:678)
	at org.cojen.maker.TheMethodMaker.invoke(TheMethodMaker.java:604)
	at Main.main(Main.java:21)
```

Main.java: 
```
import org.cojen.maker.ClassMaker;
import org.cojen.maker.MethodMaker;

import java.lang.reflect.InvocationTargetException;

public class Main {

    public static void main(String[] args) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {

        ClassMaker cm = ClassMaker.begin().public_();

        cm.addConstructor().public_();

        {
            MethodMaker mm = cm.addMethod(boolean.class, "odd", int.class).public_().static_();
            var elseLabel = mm.label();
            var n = mm.param(0);
            n.ifNe(0, elseLabel);
            mm.return_(true);
            elseLabel.here();
            mm.return_(mm.invoke("even", mm.var(Math.class).invoke("abs", n).sub(1)));
        }

        {
            MethodMaker mm = cm.addMethod(boolean.class, "even", int.class).public_().static_();
            var elseLabel = mm.label();
            var n = mm.param(0);
            n.ifNe(0, elseLabel);
            mm.return_(false);
            elseLabel.here();
            mm.return_(mm.invoke("odd", mm.var(Math.class).invoke("abs", n).sub(1)));
        }

        Class<?> clazz = cm.finish();
        var result = clazz.getMethod("even").invoke(5);
        System.out.println(result);

    }

} 
```

**Comment by clause** [comment]
Yes that works in this case.  I'm not sure if it works in the case of looking for a method handle. Maybe I've got something else wrong though. I'll see if I can track it down.
